version: "3"
services: 
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - ~/Develop/postgress_nest_data:/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres
  
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - ~/Develop/pg_admin_nest_data:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres

networks: 
  postgres:
    driver: bridge